version: "3.8"

services:

  circuitbreaker:
    image: caiodelgadonew/circuitbreaker-py
    container_name: circuitbreaker-py
    environment:
      HTTP_CLIENT: "nginx:80"
      ERROR_THRESHOLD: "3"
      TIME_WINDOW: "10"
      ACCEPT_CLIENT_ERRORS: "False"
      LOG_LEVEL: INFO
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    
